import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";
// import Script from "next/script";
// import Link from "next/link";


function Home() {
  return (
    
    <div className={styles.container}>
      <style jsx>
        {
          `
          .mySpan {
            color: blue;
          `
          }
        
      </style>
      <Head>
        <title>My Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      {/* <Script src='/src.js' strategy='lazyOnload'/> */}
      <main className={styles.main}>
        <h1 className={styles.title}>
          Blog for Hunting Coders by a <p></p>
          <span className="mySpan">
            Hunting Coder!
          </span>
        </h1>
        {/* <Image className={styles.myImg} src="/homeimg.jpg" width={450} height={300}/> */}
        <img className={styles.myImg} src="/homeimg.jpg" width={450} height={300}></img>

        <h2 className="dummy">Popular Blogs</h2>Image
        <div className="blogs">
          <div className="blog-item">
            <h3>Learn JS in 2022</h3>
            <p>JS used to design logic for web</p>
          </div>
          <div className="blog-item">
            <h3>Learn JS in 2022</h3>
            <p>JS used to design logic for web</p>
          </div>
          <div className="blog-item">
            <h3>Learn JS in 2022</h3>
            <p>JS used to design logic for web</p>
          </div>
          <div className="blog-item">
            <h3>Learn JS in 2022</h3>
            <p>JS used to design logic for web</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
            <img  src="/vercel.svg" alt="Vercel Logo" width={72} height={16}></img>

          </span>
        </a>
      </footer>
    </div>
  );
}

export default Home;
